#we want to print 10 random numbers within the range of 0 and 100 (100 inclusive)
#we import the random library because we are printing a list of RANDOM numbers
import random

#define your function
def main():
    #set the length of our proposed list of numbers
    num_random = 10

    #we set our starting value
    min_random = 0

    #we set our stopping value
    max_random = 100

    #we use a 'for' loop becuase we know the range/size of our list (i.e. 10)
    #range is an inbuilt function in python that is used to specify the length of a list
    #or number of iterations a funtion should undertake
    for i in range(num_random):

        #the variable name 'random_num' contains the random integer to be generated by our script
        #random.randint has this format random.randint(start, end)
        random_num = random.randint(min_random, max_random)

        #we get a list of 10 numbers because we combined the random.randint function with a for loop
        print(random_num)

#call the function
if __name__ == '__main__':
    main()
